

export const SUBMIT_PHONENUMBER_SUCCESS = "SUBMIT_PHONENUMBER_SUCCESS"
export const SUBMIT_PHONENUMBER_FAIL = "SUBMIT_PHONENUMBER_FAIL"

export const SUBMIT_FULLNAME_SUCCESS = "SUBMIT_FULLNAME_SUCCESS"
export const SUBMIT_VERIFICATION_SUCCESS = "SUBMIT_VERIFICATION_SUCCESS"
export const SUBMIT_NRIC_SUCCESS = "SUBMIT_NRIC_SUCCESS"
export const SUBMIT_BIRTHDAY_SUCCESS = "SUBMIT_BIRTHDAY_SUCCESS"
export const SUBMIT_EMERGENCY_SUCCESS = "SUBMIT_EMERGENCY_SUCCESS"
export const SUBMIT_PROFILE_PHOTO_SUCCESS = "SUBMIT_PROFILE_PHOTO_SUCCESS"
export const SUBMIT_GUARDIAN_CONTACT_SUCCESS = "SUBMIT_GUARDIAN_CONTACT_SUCCESS"
export const SUBMIT_GUARDIAN_RELATION_SUCCESS = "SUBMIT_GUARDIAN_RELATION_SUCCESS"

// 
export const AVATARURI_CHANGED = 'AVATARURI_CHANGED'
export const FIRSTNAME_CHANGED = 'FIRSTNAME_CHANGED'
export const LASTNAME_CHANGED = 'LASTNAME_CHANGED'
export const NRIC_CHANGED = 'NRIC_CHANGED'
export const DOB_CHANGED = 'DOB_CHANGED'
export const GENDER_CHANGED = 'GENDER_CHANGED'
export const PHONENUMBER_CHANGED = 'PHONENUMBER_CHANGED'
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const ADDRESS_CHANGED = 'ADDRESS_CHANGED'

// guardia/emergency
export const GUARDIANEMERGENCYPERSON_CHANGED = 'GUARDIANEMERGENCYPERSON_CHANGED'
export const GUARDIANEMERGENCYNUMBER_CHANGED = 'GUARDIANEMERGENCYNUMBER_CHANGED'
export const GUARDIANEMERGENCYRELATIONSHIP_CHANGED = 'GUARDIANEMERGENCYRELATIONSHIP_CHANGED'

// qualification
export const QUALIFICATION_CHANGED = 'QUALIFICATION_CHANGED'

export const PERSONALINFO_CHANGED = "PERSONALINFO_CHANGED"

export const MULTIPASS_CHANGED = "MULTIPASS_CHANGED"
export const DAYPASS_CHANGED = "DAYPASS_CHANGED"
export const SEASONPASS_CHANGED = "SEASONPASS_CHANGED"
export const PROMOPASS_CHANGED = "PROMOPASS_CHANGED"
export const PDFURL_CHANGED = "PDFURL_CHANGED"

export const SHOECART_CHANGED = "SHOECART_CHANGED"
export const SOCKCART_CHANGED = "SOCKCART_CHANGED"
export const GEARCART_CHANGED = "GEARCART_CHANGED"
export const PASSCART_CHANGED = "PASSCART_CHANGED"

export const TOTALPRICE_CHANGED = "TOTALPRICE_CHANGED"

export const PASSRECORDITEM_CHANGED = "PASSRECORDITEM_CHANGED"
export const PURCHASERECORDITEM_CHANGED = "PURCHASERECORDITEM_CHANGED"
export const USAGERECORDITEM_CHANGED = "USAGERECORDITEM_CHANGED"

export const EQUIPMENT_CHANGED = "EQUIPMENT_CHANGED"
export const VALIDPROMODATE_CHANGED = "VALIDPROMODATE_CHANGED"

export const USERINFOTHREADWORKING_CHANGED = "USERINFOTHREADWORKING_CHANGED"